[tool.black]
extend-exclude = '''/(
    \.direnv
    |\.eggs
    |\.git
    |\.hg
    |\.ipynb_checkpoints
    |\.mypy_cache
    |\.nox
    |\.pytest_cache
    |\.ruff_cache
    |\.tox
    |\.svn
    |\.venv
    |\.vscode
    |__pypackages__
    |_build
    |buck-out
    |build
    |dist
    |venv
    |patches
)/'''